sonar.projectKey=Bhukyapoojitha_poc-07-inventory-management
sonar.organization=bhukyapoojitha

sonar.projectName=poc-07-inventory-management

sonar.sources=app,rag

sonar.exclusions=tests/**,tests/**/*,chroma_db/**
sonar.cpd.exclusions=tests/**,tests/**/*